### PR TITLE
Added travis ci support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by leo** [comment]
So... `node_js: node` runs the tests on the latest stable node version. Isn't that enough?

😊

**Comment by amilajack** [comment]
Fixed

**Comment by leo** [comment]
I'm sorry, but I really don't understand the difference between the current setup and your solution. The only different thing I can see is that you're caching the `node_modules` directory. 😄

**Comment by amilajack** [comment]
Should I add node version 4 along with 'node'? That would make more sense.

**Comment by leo** [comment]
Node. I don't want to support that node version... 😊

**Pull request closed without merging**
